# https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration

name = 'hugo-pico-theme'
license = 'BSD-2-Clause-Patent'
licenselink = 'https://opensource.org/license/bsd-2-clause-patent'
description = 'experimental theme'

homepage = 'https://github.com/aetos382/hugo-pico-theme'

demosite = 'https://aetos382.github.io/hugo-pico-theme/'

tags = ['blog']
features = []

[author]
  name = 'aetos'
  homepage = 'https://github.com/aetos382'

[original]
  author = 'aetos'
  homepage = 'https://github.com/aetos382/hugo-pico-theme'
  repo = 'https://github.com/aetos382/hugo-pico-theme.git'
