name: publish-demo-site

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      HUGO_VERSION: '0.160.1'
      DART_SASS_VERSION: '1.99.0'
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          lfs: true

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'demo-site/go.mod'
          cache-dependency-path: 'demo-site/go.sum'

      - name: Create directories
        run: |
          set -euo pipefail
          mkdir -p ${GITHUB_WORKSPACE}/bin
          echo "${GITHUB_WORKSPACE}/bin/" >> $GITHUB_PATH

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache-tools
        with:
          path: ${{ github.workspace }}/bin
          key: tools-hugo-${{ env.HUGO_VERSION }}-sass-${{ env.DART_SASS_VERSION }}

      - name: Install Hugo
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          curl --retry 3 --retry-delay 5 -qfsSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz | tar -C ${GITHUB_WORKSPACE}/bin/ -xz hugo

      - name: Install Dart Sass
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          curl --retry 3 --retry-delay 5 -qfsSL https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz | tar -C ${GITHUB_WORKSPACE}/bin/ -xz --strip-components=1

      - name: Verify installations
        run: |
          set -euo pipefail
          git version | echo "git: $(cat -)"
          git lfs version | echo "git lfs: $(cat -)"
          hugo version | echo "hugo: $(cat -)"
          sass --version | echo "dart-sass: $(cat -)"
          go version | echo "go: $(cat -)"

      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
        id: pages

      - name: Build
        working-directory: demo-site
        run: >
          hugo build
          --baseURL ${{ steps.pages.outputs.base_url }}

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: demo-site/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        id: deployment
